<!--
 * @Description: http 请求
 * @Date: 2021-07-07 20:32:45
 * @LastEditTime: 2021-07-07 20:32:46
-->


###
POST http://localhost:5000/user/login
content-type: application/json;charset=UTF-8

{
    "username":"admin",
    "password":"admin"
}
### 

GET http://localhost:5000/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYyNTk2NDUzNiwiZXhwIjoxNjI2MDUwOTM2fQ.mF470Vn5pQBfba4wVXEkB9OwV3IANsI27tXUUmrEsfQ
###

POST  http://localhost:5000/user/create
content-type: application/json;charset=UTF-8

{
    "username":"del",
    "password":"admin"
}


### 
POST  http://localhost:5000/user/del
content-type: application/json;charset=UTF-8

{
    "username":"del"
}